service: musubi-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: ${opt:stage, 'development'}
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:provider.stage}}
  httpApi:
    cors: true

plugins:
  - serverless-offline
  - serverless-esbuild

functions:
  http:
    handler: awsLambdaTestHandlerHttp.handler
    events:
      - httpApi:
          cors: true
          path: /http/{path+}
          method: any
  rest:
    handler: awsLambdaTestHandlerRest.handler
    events:
      - http:
          path: /rest/{path+}
          method: any
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: inline
  stages:
    - development
    - production
  logRetentionInDays:
    production: 90
    development: 30
    staging: 30
