name: Test, build and release
on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - '*'

jobs:
  browser-extension-e2e:
    name: Browser Extension E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npx nx run examples-browser-extension:build

      - name: Run tests
        run: npx nx run examples-browser-extension-e2e:e2e

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 18, 19 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npx nx run-many --target=lint --all

      - name: Build
        run: npx nx run-many --target=build --all --skip-nx-cache

      - name: Run tests
        run: npx nx run-many --target=test --all --configuration=ci
  release:
    if: github.ref == 'refs/heads/main'
    name: Build & Release
    runs-on: ubuntu-latest
    needs:
      - test
      - browser-extension-e2e
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'

      - name: Configure CI Git User
        run: |
          git config --global user.name 'TheUnderScorer'
          git config --global user.email 'przemyslawzydek@gmail.com'
          git remote set-url origin https://TheUnderScorer:$GITHUB_TOKEN@github.com/TheUnderScorer/nx-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install npm dependencies
        run: npm ci

      - name: Print versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "NX version: $(npx nx --version)"

      - name: Release
        run: npx nx run-many --target=semantic-release --all --parallel --maxParallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
