name: Release
on:
  push:
    branches:
      - main
      - test

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'

      - name: Configure CI Git User
        run: |
          git config --global user.name 'TheUnderScorer'
          git config --global user.email 'przemyslawzydek@gmail.com'
          git remote set-url origin https://TheUnderScorer:$GITHUB_TOKEN@github.com/TheUnderScorer/nx-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install npm dependencies
        run: npm ci

      - name: Print versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "NX version: $(npx nx --version)"

      - name: Lint
        run: npx nx run-many --target=lint --all

      - name: Run tests
        run: npx nx run-many --target=test --all

      - name: Release
        run: npx nx run-many --target=semantic-release --all --parallel --maxParallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
